### ISSUE TITLE
ERROR: No X-COM installations found

### ISSUE THREAD

**Issue by probonopd** [knapsu/OpenXcom-AppImage#1]
Getting

> ERROR: No X-COM installations found

when trying to run `OpenXcom_201706261605_x86-64.AppImage` on `linuxmint-18-cinnamon-64bit.iso`

![screenshot from 2017-06-26 19-50-42](https://user-images.githubusercontent.com/2480569/27552792-f6855254-5aa8-11e7-87d0-89f9d3400d85.png)

**Comment by knapsu** [comment]
This message is expected as OpenXcom requires resources (graphics, music) from the original game (DOS / Windows / Steam version).
This requirement is written on the [Wiki page](http://ufopaedia.org/index.php/Installing_(OpenXcom)).

Copying game resources to `$HOME/.openxcom` or `$HOME/.local/share/openxcom` makes the game work as expected.

Unfortunately I can not do anything about this.
